### ISSUE TITLE
Stop on a specific breakpoint for more than one time.

### ISSUE THREAD

**Issue by panzhongxian** [mostafa/goja_debugger#5]
Hi, @mostafa . I read the code and I found the deubgger is hold on very time the `pc` is update and if the file and the line matched, this will throw a break reason. Am I right?

But there are some common cases that one simple line will be compiled into multiple expressions. For example:

```javascript
a = 0
```

The compiler will compile the code into three express:

```
compileExpression: [*ast.AssignExpression] &{= 0xc000601a70 0xc000379590}
compileExpression: [*ast.Identifier] &{a 1}
compileExpression: [*ast.NumberLiteral] &{3 0 0}
```

This will lead to that when the `pc` becomes from 1 to 3, the debugger will be broken for 3 times on the same breakpoint - line 1.

Do you have any advice for solve the problem?

**Comment by mostafa** [comment]
Hey @panzhongxian,

have you read the PR and the issue mentioned on the README?
AFAIK, the `pc` is updated by each new instructions and it's really hard to map instructions to lines of code. The source map has its own set of issues and finding the correct line and stopping and continuing needs a few changes in the Goja itself to work. I could have written my own source map implementation inside the Goja compiler/VM, but it was unnecessary and would add more problems than it solves.

**Comment by panzhongxian** [comment]
Thanks for your reply. I am sorry for my reckless question without reading the PR carefully.
What I asked should be related to your https://github.com/mostafa/goja/tree/debugger branch.

I can understand the compiling is done in the Goja.

There are several kind of pc to line mapping problems there. But what I metioned here is **one line with multiple `pc`**.

Without changing Goja compiler, we can avoid continue will to the same line many times by store the latest breakpoint info and add updating action here https://github.com/mostafa/goja/blob/debugger/vm.go#L438


Changing as follow(which is ugly but works):

```go
checkSameBreakpoint := func() bool {
	return vm.debugger.lastBreakpoint.filename == vm.debugger.Filename() &&
		vm.debugger.lastBreakpoint.line == vm.debugger.Line()
}

if vm.debugger == nil {
	vm.prg.code[vm.pc].exec(vm)
} else if !vm.debugger.active && vm.debugger.breakpoint() && !checkSameBreakpoint() {
	vm.debugger.lastBreakpoint.filename = vm.debugger.Filename()
	vm.debugger.lastBreakpoint.line = vm.debugger.Line()
	vm.debugger.updateCurrentLine()
	vm.debugger.activate(BreakpointActivation)
	vm.prg.code[vm.pc].exec(vm)
} else {
	if !checkSameBreakpoint() {
		vm.debugger.lastBreakpoint.filename = ""
		vm.debugger.lastBreakpoint.line = -1
	}
	vm.prg.code[vm.pc].exec(vm)
}
```

Corresponding to the change, the struct Debugger should add a new member:

```go
type Debugger struct {
	vm *vm

	currentLine    int
	lastLine       int
	breakpoints    map[string][]int
	activationCh   chan chan ActivationReason
	currentCh      chan ActivationReason
	active         bool
	lastBreakpoint struct {
		filename string
		line     int
	}
}
```

**Comment by mostafa** [comment]
@panzhongxian 
That's a good idea. Just send a PR and let me review/merge it. If you could also write a unit-test, it would be awesome. 🙏

**Comment by panzhongxian** [comment]
OK.
I found this solution didn't work in nested function call cases. For example:

```javascript
function HelloDebugger() {
    const o = {
        a: 123,
        b: 666,
    };
}

function AAA() {
    return HelloDebugger();
}

function BBB() {
    return AAA();   // <--- set breakpoint on this line.
}
```
I tried to solve this problem with stack but failed, because with the limited info I could not distinguish the breakpoint on a nested function call or the breakpoint on a statement inside `for`-loop.

**Comment by mostafa** [comment]
Nested function calls reset `pc` and this messes everything up. That is, function body is considered local scope and a local `pc` is used and this local `pc` messes line info and other related calculations. That is true, unless https://github.com/dop251/goja/commit/acd374ca9c94245931af35a29e47cfedc43da5b5 fixes it.

**Comment by panzhongxian** [comment]
OK. The issue [#347](https://github.com/dop251/goja/issues/347) fixed by the commit you mentioned is also posted by me. ;)

I'm excited to tell your after I merged the dop251/goja master to debugger branch, the anonymous function could be debugged inside.

Please review the pull request [Merge to dop251/goja master. #8](https://github.com/mostafa/goja/pull/8) first. After that, you could handle the [Stop only one time on per breakpoint #7](https://github.com/mostafa/goja/pull/7)

**Comment by mostafa** [comment]
I saw what you did there! Well done! I'll review them as soon as I can.

**Comment by mostafa** [comment]
@panzhongxian Fetched and merged from the latest goja's upstream branch (master) and merged your changes.

**Comment by panzhongxian** [comment]
OK. I saw you have done that. I will follow the flow next time.

**Comment by panzhongxian** [comment]
@mostafa 
Please enable ISSUE in mostafa/goja repo. I have more advice and enhance changing.

**Comment by mostafa** [comment]
@panzhongxian Done! ✅

**Comment by mostafa** [comment]
I'll close this issue, since I think it's resolved. Feel free to reopen if necessary
